config/routes.rb
Rails.application.routes.draw do
  root to: "welcome#index"
  resources :loans, only: [:index, :show]
  resources :categories, only: [:show]
  post "/cart_items", to: "cart_items#create"
  get "/cart", to: "cart_items#index"
  put "/cart_items/:id", to: "cart_items#update"
  get "/login", to: "sessions#new"
  post "/login", to: "sessions#create"
  get "/dashboard", to: "users#show"
  delete "/logout", to: "sessions#destroy"
  get "/register", to: "users#new"
  post "/register", to: "users#create"
  delete "/cart_items/:id", to: "cart_items#destroy"
  namespace :admin do
    resources :loans, only: [:index, :new, :create, :edit, :update]
    resources :orders, only: [:update]
    get "/dashboard", to: "admins#show"
    get "/edit", to: "admins#edit"
    put "/edit", to: "admins#update"
  end

  resources :orders, only: [:new, :create, :show]
end

app/models/cart.rb
class Cart
  attr_reader :cart
  def initialize(cart_data)
    cart_data ||= Hash.new(0)
    @cart = cart_data
  end

  def add_item(params)
    loan = Loan.find(params[:loan_id].to_i)
    @cart[loan.id.to_s] ||= 0
    @cart[loan.id.to_s] += 1
  end

  def data
    @cart
  end

  def items
    @cart.map do |key, quantity|
      item = Loan.find(key.to_i)
      CartItem.new(item, quantity)
    end
  end

  def total
    items.map(&:subtotal).sum
  end
end

app/models/cart_item.rb
class CartItem < SimpleDelegator
  attr_reader :loan, :quantity

  def initialize(item, quantity)
    if quantity < 0
      quantity = 0
    end

    @loan = item
    @quantity = quantity
  end

  def subtotal
    @loan.price * @quantity
  end
end

app/models/category.rb
class Category < ActiveRecord::Base
  has_many :loans
  validates :name, presence: true, uniqueness: true
end

app/models/loan.rb
class Loan < ActiveRecord::Base
  validates :title, presence: true, uniqueness: true
  validates :description, presence: true
  validates :price, presence: true, numericality: { greater_than: 0 }
  validates :category, presence: true

  belongs_to :category
  has_attached_file :avatar,
                    styles: { medium: "800x300#", thumb: "320x150#" },
                    default_url: "https://s3.amazonaws.com/turing-denvestments/assets/Richard_Stallman_by_Anders_Brenna_01.jpg"
  validates_attachment_content_type :avatar, content_type: /\Aimage\/.*\Z/
end

app/models/loan_quantities.rb
class LoanQuantities
  def initialize(order)
    @order = order
  end

  def loan_id_quantities
    Hash[@order.order_items.pluck(:loan_id, :quantity)]
  end

  def loans_and_quantities
    loan_id_quantities.map do |id, quantity|
      [Loan.find(id), quantity]
    end
  end

  def loan_quantities
    Hash[loans_and_quantities]
  end
end

app/models/order.rb
class Order < ActiveRecord::Base
  has_many :order_items
  belongs_to :user
  validates :user_id, presence: true
  validates :status,
            presence: true,
            inclusion: { in: %w( Ordered Paid Cancelled Completed),
                         message: "%{value} is not a valid status" }
  validates :card_number, presence: true
  validates :card_expiration, presence: true
  def date
    created_at.strftime("%b %d, %Y")
  end
end

app/models/order_item.rb
class OrderItem < ActiveRecord::Base
  belongs_to :order
  belongs_to :loan
end

app/models/status.rb
class Status < ActiveRecord::Base
  has_many :orders
end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :orders
  validates :username, presence: true, uniqueness: true
  validates :full_name, presence: true
  validates :address, presence: true
  has_secure_password

  enum role: %w(default admin)
end

app/models/user_order.rb
class UserOrder
  def initialize(session, params)
    @session = session
    @params = params
  end

  def create_order
    @order = Order.create(user_id: @session[:user_id],
                          card_number: @params[:order][:card_number],
                          card_expiration: @params[:order][:card_expiration],
                          total_cost: Cart.new(@session[:cart]).total,
                          status: "Ordered")
  end

  def create_order_items
    @session[:cart].each do |loan_id, quantity|
      OrderItem.create(loan_id: loan_id,
                       quantity: quantity,
                       order_id: @order.id)
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  helper_method :category_list, :current_user, :cart

  def category_list
    Category.all
  end

  def current_admin?
    current_user && current_user.admin?
  end

  def current_user
    User.find(session[:user_id]) if session[:user_id]
  end

  def cart
    Cart.new(session[:cart])
  end

  def show_order?(order_user_id)
    (current_user) && (current_user.id == order_user_id) || (current_admin?)
  end
end

app/controllers/cart_items_controller.rb
class CartItemsController < ApplicationController
  def create
    loan_cart = cart
    loan_cart.add_item(params)
    session[:cart] = loan_cart.data
    redirect(params)
  end

  def index
    @items = cart.items
    @total = cart.total
  end

  def update
    change_quantity(params)
    redirect_to "/cart"
  end

  def destroy
    delete_item(params)
    delete_notice
    redirect_to "/cart"
  end

  private

  def redirect(params)
    redirect_to params[:path]
  end

  def change_quantity(params)
    session[:cart][params[:id]] = params[:item_quantity][:quantity].to_i
  end

  def delete_item(params)
    cart = session[:cart]
    cart.delete(params[:id])
  end

  def delete_notice
    loan = Loan.find(params[:id])
    flash[:notice] = "Successfully removed <a href=/loans/#{params[:id]}>
      #{loan.title}</a> from your cart."
  end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  def show
    @category = Category.find(params[:id])
    @loans = @category.loans
  end
end

app/controllers/loans_controller.rb
class LoansController < ApplicationController
  def index
    @loans = Loan.all
  end

  def show
    @loan = Loan.find(params[:id])
  end
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
  def new
    if current_user
      @orders = Order.new
    else
      flash[:notice] = "Please Login or Create an Account to Checkout"
      redirect_to login_path
    end
  end

  def create
    user_order = UserOrder.new(session, params)
    @order = user_order.create_order
    user_order.create_order_items
    session[:cart].clear
    flash[:notice] = "Order successful!"
    redirect_to order_path(@order.id)
  end

  def show
    order = Order.find(params[:id])
    if show_order?(order.user_id)
      @order = order
      @user = User.find(order.user_id)
      loan_quantity = LoanQuantities.new(order)
      @loan_quantities = loan_quantity.loan_quantities
    else
      render file: "/public/404"
    end
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    user = User.find_by(username: user_params[:username])
    if user && user.authenticate(user_params[:password])
      session[:user_id] = user.id
      redirect_to "/dashboard"
    else
      flash[:notice] = "Incorrect login"
      render :new
    end
  end

  def destroy
    session[:user_id] = nil
    session[:cart] = nil
    redirect_to root_path
  end

  private

  def user_params
    params.require(:user).permit(:username, :password)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    if !current_user
      redirect_to "/"
    elsif
      current_admin?
      redirect_to "/admin/dashboard"
    end
  end

  def new
    @user = User.new
  end

  def create
    user = User.new(user_params)
    if user.save
      session[:user_id] = user.id
      redirect_to dashboard_path
    else
      flash[:notice] = user.errors.full_messages.join(", ")
      render :new
    end
  end

  private

  def user_params
    params.require(:user).permit(:username, :password, :full_name, :address)
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/loans_helper.rb
module LoansHelper
end

app/views/admin/admins/edit.html.erb
<%= flash[:notice] %>

<div class="container">
  <%= form_for :admin, url: "/admin/edit",
                       method: :put,
                       html: { class: "form-horizontal center" } do |f| %>
    <div class="form-group col-md-12">
      <%= f.label :username, class: "control-label" %>
      <%= f.text_field :username, class: "form-control" %>
    </div>
    <div class="form-group col-md-12">
      <%= f.label :password, class: "control-label" %>
      <%= f.password_field :password, class: "form-control" %>
    </div>
    <div class="form-group col-md-12">
      <%= f.label :full_name, class: "control-label" %>
      <%= f.text_field :full_name, class: "form-control" %>
    </div>
    <div class="form-group col-md-12">
      <%= f.label :address, class: "control-label" %>
      <%= f.text_field :address, class: "form-control" %>
    </div>
    <%= f.submit %>
  <% end %>
</div>

app/views/admin/admins/show.html.erb
<body class="full">
  <div class="container">
    <div class="col-md-8 col-md-offset-2">
      <h1>Admin Dashboard</h1>
      <p class="lead">Hello, <%= User.find(session[:user_id]).username.upcase %>!</p>
      <div id="admin-links" class="row col-md-10">
        <span class="btn btn-warning btn-md"><%= link_to "Edit My Profile", admin_edit_path %></span>
        <span class="btn btn-primary btn-md"><%= link_to "View Loans", admin_loans_path %></span>
      </div>
      <div class="btn-group">
        <button type="button" class="btn btn-default" id="ordered">Ordered</button>
        <button type="button" class="btn btn-default" id="cancelled">Cancelled</button>
        <button type="button" class="btn btn-default" id="paid">Paid</button>
        <button type="button" class="btn btn-default" id="completed">Completed</button>
      </div>

      <div class="hidden orders" id="Ordered">
        <ul class="list-group">
          <li class="list-group-item lead">Status: Ordered - <%= @ordered.size %></li>
          <% @ordered.each do |order| %>
          <li class="list-group-item"><%= link_to "Order ID: #{order.id}", order_path(order) %>
             | <%= link_to "Cancel", admin_order_path(order, status: "cancelled"), method: :put %>
           | <%= link_to "Mark as Paid", admin_order_path(order, status: "paid"), method: :put %></li>
          <% end %>
        </ul>
      </div>
      <div class="hidden orders" id="Cancelled">
        <ul class="list-group">
          <li class="list-group-item lead">Status: Cancelled - <%= @cancelled.size %></li>
          <% @cancelled.each do |order| %>
          <li class="list-group-item"><%= link_to "Order ID: #{order.id}", order_path(order) %></li>
          <% end %>
        </ul>
      </div>
      <div class="hidden orders" id="Paid">
        <ul class="list-group">
          <li class=" list-group-item lead">Status: Paid - <%= @paid.size %></li>
          <% @paid.each do |order| %>
          <li class="list-group-item"><%= link_to "Order ID: #{order.id}", order_path(order) %>
             | <%= link_to "Cancel", admin_order_path(order, status: "cancelled"), method: :put %>
           | <%= link_to "Mark as Completed", admin_order_path(order, status: "completed"), method: :put %></li>
          <% end %>
        </ul>
      </div>
      <div class="hidden orders" id="Completed">
        <ul class="list-group">
          <li class=" list-group-item lead">Status: Completed - <%= @completed.size %></li>
          <% @completed.each do |order| %>
          <li class="list-group-item"><%= link_to "Order ID: #{order.id}", order_path(order) %></li>
          <% end %>
        </ul>
      </div>
    </div>
  </div>
</body>

<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.1/jquery.min.js"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.2.0/js/bootstrap.min.js"></script>
<script src="adminorders.js"></script>

app/views/layouts/_flash.html.erb
<% if notice = flash[:notice] %>
  <div class="alert alert-warning" role="alert">
    <%= notice %>
  </div>
<% end %>

app/views/layouts/_login.html.erb
<% if current_user && !current_user.admin?%>
    <li><%= link_to current_user.username, dashboard_path %></li>
    <li><%= link_to "Log Out", logout_path, method: :delete %></li>
<% elsif current_user && current_user.admin?%>
    <li><%= link_to current_user.username, admin_dashboard_path %></li>
    <li><%= link_to "Log Out", logout_path, method: :delete %></li>
<% else %>
    <li><a href="/login">Log In</a></li>
    <li><a href="/register">Create Account</a></li>
<% end %>

app/views/layouts/_navbar.html.erb
<nav class="col-md-12 navbar navbar-inverse navbar-fixed-top">
  <div class="container-fluid">
    <a class="navbar-brand" href="/">Denvestments</a>
    <ul class="nav navbar-nav">
      <li><a href="/loans">Loans</a></li>
      <li class="dropdown">
        <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button"
        aria-haspopup="true" aria-expanded="false">Categories<span class="caret">
        </span>
        </a>
        <ul class="dropdown-menu">
          <% category_list.each do |category| %>
          <li><a href="<%= category_path(category) %>"><%= category.name %></a></li>
          <% end %>
        </ul>
      </li>
    </ul>
    <ul class="nav navbar-nav navbar-right">
      <%= render partial: "layouts/login" %>
      <li><a href="/cart">Loans in Cart: <%= session[:cart].values.sum if session[:cart] %></a></li>
      <li><a id="cart" href="/cart"><span class="glyphicon glyphicon-shopping-cart"></span></a></li>
    </ul>
  </div>
</nav>

<script>
    $(document).ready(function () {
        $('.dropdown-toggle').dropdown();
    });
</script>

app/views/layouts/_tiny_loan.html.erb
<div class="col-sm-4">
  <div class="thumbnail">
    <%= image_tag loan.avatar.url %>
    <div class="caption">
      <h4 class="pull-right"><%= number_to_currency(loan.price) %></h4>
      <h4><%= link_to loan.title, loan_path(loan.id) %></h4>
      <p><%= loan.description %></p>
      <% if mode == :add %>
        <%= button_to "Add to Cart", cart_items_path(loan_id: loan.id,
                                                     path: path) %>
      <% elsif mode == :edit %>
        <%= link_to "Edit", edit_admin_loan_path(loan) %>
      <% end %>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Denvestments</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => false %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= render partial: "layouts/navbar" %>
<%= yield %>

</body>
</html>